### ISSUE TITLE
ローカル環境とGitHub Pagesとで箇条書きの見え方が違う事象を解決する

### ISSUE THREAD

**Issue by ftnext** [ftnext/2021_slides#19]
* build/revealjs （ローカルでの練習で使う）
* docs/ （GitHub Pages。本番で使う）

docsの方は、箇条書きの各itemの上下に余白が入って縦に長く見える

**Comment by ftnext** [comment]
Sphinxが生成する `basic.css` がdocsの下に配置されていなかったのが原因

```html
    <link rel="stylesheet" href="../_static/basic.css" type="text/css" />
```

→basic.cssをコピーして配置したところ、解消した

basic.cssでは、simpleクラスの付いた箇条書きの下の、liの下の、pのmargin-{top,bottom}を0に設定（縦が短くなる）

```css
ol.simple > li:not(:first-child) > p,
ul.simple > li:not(:first-child) > p {
    margin-top: 0;
}

ol.simple p,
ul.simple p {
    margin-bottom: 0;
}
```
