### ISSUE TITLE
**での強調箇所に色を付けたい（カスタムCSSを個別スライドに適用）

### ISSUE THREAD

**Issue by ftnext** [ftnext/2021_slides#7]
白い文字色のままだと地の文と区別がつかないと感じている。
Azusa 3でやっているみたく、緑にしたい

CSSとしてはレベルを変えて複数設定することになる

**Comment by ftnext** [comment]
複数のCSSは対応できないようなので、暫定対応として共通のCSSで設定。
マークダウンで強調した箇所は、スライドでは`<strong>`タグでマークアップされている

```css
.reveal strong {
  color: #<color code>;
}
```

GitHub Pagesへの反映は別のIssueで（`deployslide`コマンドの機能追加として）

テーマごとに強調に使う色は異なる（背景が緑ならAzusa 3でやっているような緑色は選ばない）
→実装を確認し、本家の方に提案を送ってみる（スライドごとにCSSを追加できるのが理想と考える）
